### ISSUE TITLE
Slack webhook token is a secret

### ISSUE THREAD

**Issue by eRaMvn** [domain-protect/domain-protect#184]
Hi,

I was a looking at the code, and I saw slack webhook url is not being stored as secret [here](https://github.com/domain-protect/domain-protect/blob/main/lambda_code/notify/notify.py#L294) and [here](https://github.com/domain-protect/domain-protect/blob/main/terraform.tfvars.example#L4). It is being stored as environment variable in lambda function, and for companies that uses atlantis to deploy infrastructure, the terraform.tfvars is also committed. Gitleaks detects slack webhook urls as secrets, and it also says here as well https://api.slack.com/messaging/webhooks#:~:text=Your%20webhook%20URL%20contains%20a,out%20and%20revokes%20leaked%20secrets.

I would say we should use something like the function below to retrieve the secret from SSM Parameter store or secret manager
```
def get_secret(secret_name):
    ssm_client = boto3.client('ssm')

    try:
        response = ssm_client.get_parameter(
            Name=secret_name,
            WithDecryption=True,
        )
        return response['Parameter']['Value']
    except Exception as e:
        lambda_logger.error(f"Failed to retrieve secret {secret_name} because {e}")
    return
```

**Comment by paulschwarzenberger** [comment]
Thanks @eRaMvn this would be a significant security improvement, and applies to BugCrowd, Cloudflare and HackerOne API tokens as well (if those integrations are chosen)
