### ISSUE TITLE
False positive in Elastic Beanstalk Alias detection

### ISSUE THREAD

**Issue by ignacio-halborn** [domain-protect/domain-protect#228]
AWS do not allow specifying domains that start with `eba-` when creating a elastic beanstalk application. It will return the error `Value eba-8cahe6rt at 'CNAMEPrefix' failed to satisfy constraint: Member Don't start domain name with 'eba-' (reserved).` 
Therefore, dangling records for elastic beanstalk domains that start with `eba-` should be filtered out of the results. I suggest marking them as a warning as the DNS record should be cleaned up but it has no security implication.

**Comment by paulschwarzenberger** [comment]
I've tested this and get the same result
