### ISSUE TITLE
KeyError: 'ResourceRecords' Issue in manual_scans/aws/aws-cname-s3.py

### ISSUE THREAD

**Issue by awakenine** [domain-protect/domain-protect#234]
During the scan record set 'r' sometimes has the following structure
`{'Name': 'sub.domain.com.', 'Type': 'CNAME', 'AliasTarget': {'HostedZoneId': 'SOMEZONEID', 'DNSName': 'otherasubdomain.domain.com.', 'EvaluateTargetHealth': False}}`
Which causes error `KeyError: 'ResourceRecords` and crash script. 
The possible solution would be catch exception or check if ResourceRecords exist in andvance.

The issue occurs on the line 
[                and "amazonaws.com" in r["ResourceRecords"][0]["Value"]](https://github.com/domain-protect/domain-protect/blob/a9227e8a03e9205e198733382209e71ca136af05/manual_scans/aws/aws-cname-s3.py#L52)

The issue is the same for all scripts
[aws-cname*.py](https://github.com/domain-protect/domain-protect/blob/main/manual_scans/aws/)

I added check on line 51 as a fast fix, but not sure that we should ignore Alias records.

if r["Type"] in ["CNAME"] and r.get("ResourceRecords")

**Comment by paulschwarzenberger** [comment]
@awakenine thanks for raising this issue, I'll take a look at this

**Comment by awakenine** [comment]
He @paulschwarzenberger, 
I found this issue on already working cloud during an audit, so it may be hard to reproduce.

I see elements in resulting JSON without ResourceRecords key.
Try the following to reproduce:
Go to https://us-east-1.console.aws.amazon.com/route53/v2/hostedzones and create record like on screenshot.
Check Alias switch and chose Record Type: CNAME – Routes traffic to another domain name and to some AWS resources
Let me know if it help. 
![image](https://github.com/domain-protect/domain-protect/assets/28957954/28b1d01c-9677-412a-b08a-47d28e95d556)

**Comment by paulschwarzenberger** [comment]
Thanks, yes, that resulted in the same error. Now I've replicated, I'll work on a fix to the manual scans, and also see whether that causes the same error in the Lambda function implementation of Domain Protect
