### ISSUE TITLE
Support permissions_boundary in aws_iam_role

### ISSUE THREAD

**Issue by com6056** [domain-protect/domain-protect#237]
The `aws_iam_role` resources in the modules should support the `permissions_boundary` parameter.

**Comment by paulschwarzenberger** [comment]
@com6056 thanks for raising this issue - can you please elaborate on which IAM roles you want to add a permissions boundary to? Are you referring to:
- the IAM role which Domain Protect assumes in every AWS account in the org
- the IAM roles associated with the components of Domain Protect, e.g. a Lambda function

It would also be useful to understand why you want to add a permissions boundary, and what you would want to specify in the permissions boundary.

**Comment by com6056** [comment]
All of the IAM roles, all we need is the ability to set the `permissions_boundary` parameter on the `aws_iam_role` resources that are created: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role?ref=gitguardian-blog-automated-secrets-detection#permissions_boundary

We use permissions boundary to ensure there is no privilege escalation in our Terraform environment, so every role created by our Terraform service account is required to have this permissions boundary attached to it.

We don't need the modules to create the boundary, just allow us to set the ARN to an already existing boundary.

For now we've just vendored the module and modified it like so:
```
resource "aws_iam_role" "lambda" {
  name                 = "${var.project}-${local.role_name}-${local.env}"
  permissions_boundary = data.aws_iam_policy.terraform_permissions_boundary.arn
  assume_role_policy   = templatefile("${path.module}/templates/${var.assume_role_policy}_role.json.tpl", { project = var.project })
  managed_policy_arns  = var.takeover ? ["arn:aws:iam::aws:policy/AmazonVPCFullAccess", "arn:aws:iam::aws:policy/AdministratorAccess-AWSElasticBeanstalk", "arn:aws:iam::aws:policy/AmazonS3FullAccess", "arn:aws:iam::aws:policy/AWSCloudFormationFullAccess"] : []
}
```

But ideally it would be awesome if we could just pass the permissions boundary ARN via a parameter in the module or something instead.

Thanks!

**Comment by paulschwarzenberger** [comment]
@com6056 sounds perfectly reasonable! Would you like to submit a PR for this feature?

**Comment by com6056** [comment]
Yep! I can get that going 🙌

**Comment by com6056** [comment]
Submitted https://github.com/domain-protect/domain-protect/pull/240 🎉
