### ISSUE TITLE
Update scan doesn't detect A records fixed by deleting record and star record existing

### ISSUE THREAD

**Issue by com6056** [domain-protect/domain-protect#239]
It looks like the only way domain-protect detects if an A record was deleted is by trying to actually resolve it: https://github.com/domain-protect/domain-protect/blob/ae029055bf69bd1686ec2cef1d1bd4359e7796a9/utils/utils_dns.py#L100-L113

In our case, we have a star record in place that means that if we delete a vulnerable record, it will still resolve due to the star record.

For example:

1. We have a star record in place such as `*.example.com` pointing to non-vulnerable IP.
2. domain-protect scans `vulnerable.example.com`, marks it as vulnerable.
3. We delete the vulnerable `vulnerable.example.com` A record
4. domain-protect doesn't correctly identify it as fixed since it doesn't think it was deleted since it still resolves

**Comment by paulschwarzenberger** [comment]
@com6056 thanks for raising this issue!
As a workaround, you can manually enter your own fixed date into the Domain Protect DynamoDB Table for the relevant domain.
Do you think it's worth fixing in code, given it's somewhat of an edge case?
If so, do you have any suggestion for how best to do it?
