### ISSUE TITLE
possible bug in Registered Domain check

### ISSUE THREAD

**Issue by cleo2525** [domain-protect/domain-protect#274]
We are getting false positives with the Registered Domains check in Domain Protect. We have several domain names that use Route53 registered domains as their registrar, but their DNS zones are not hosted in Route53. 

Could Domain Protect skip any domain names that don't have AWS servers set as their name servers?

In addition, would it be possible to mark a registered domain as "OK" in the DynamoDB database (like we can do for IPs). This would reduce the false positives when a registered domain resides in your AWS account, but the zones are hosted in a partner's AWS account.

**Comment by paulschwarzenberger** [comment]
@cleo2525 thanks for raising this issue. It shouldn't make any difference whether the Registered Domains hosted zones are in the same AWS organisation, a different AWS org, or another DNS provider - Domain Protect just does a DNS check.

Can you please let me have details of one or two of the domains where you're seeing a false positive, so I can investigate further? If you don't want to make them public, you can send the details to me at paul@celidor.net or via CloudSecurityForum Slack.

**Comment by paulschwarzenberger** [comment]
After some discussion on Slack, this was due to an engineer not following DNS standards. The recommended approach for parked domains is to delegate registered domains to a standard hosted zones and follow the [NCSC Guidelines for Parked Domains](https://www.ncsc.gov.uk/blog-post/protecting-parked-domains)
