### ISSUE TITLE
Option to override local.env

### ISSUE THREAD

**Issue by adampie** [domain-protect/domain-protect#276]
We use Terraform Cloud for managing workspaces and I've found that migrating states to a new workspace will require most resources to be recreated; due to `lower(terraform.workspace)`. 

Example of an AWS Lambda name change:
```text
"domain-protect-accounts-default" 

change to 

"domain-protect-accounts-{COMPANY_PREFIX}-terraform-domain-protect"
```

Could an override be added for local.env to prevent resources getting renamed and also potentially to not hit any resource name character limits?

I think something like this might work:
```hcl
locals {
  env = var.env_override != "" ? var.env_override : lower(terraform.workspace)
}

variable "env_override " {
  default = ""
}
```

Ta!

**Comment by paulschwarzenberger** [comment]
Hi @adampie thanks for raising this issue, it's a very good idea to update this to allow more flexibility. I think the first step should be removal of `local.env` from all the Terraform modules, and to pass in a Terraform variable `environment` from the top level `main.tf` to each module.
Then implement the change you've proposed, along with an update to any points where there are conditional Terraform statements relying on `local.env`, for example, takeover only turned on in `prd`
Is this something you'd like to contribute?
So we can collaborate effectively, please contact me via Slack, either using the OWASP Slack workspace or Cloud Security Forum Slack workspace.
For OWASP you can sign up [here](https://owasp.org/slack/invite), for Cloud Security Forum you can email me at @paul@celidor.net and I'll send you an invite.

**Comment by adampie** [comment]
Sure, happy to help. 

Pinged you an email.
