### ISSUE TITLE
Modularize and publish terraform module in registry

### ISSUE THREAD

**Issue by nitrocode** [domain-protect/domain-protect#277]
The module in the root of the domain-protect repo directory just needs to be submitted to https://registry.terraform.io/

That way we can use something like this

```hcl
module "domain_protect" {
  source  = "domain-protect/domain-protect/aws"
  version = "0.0.1"

  # input variables
}
```

The repo would need to be renamed or a new repo would need to be created with this convention `domain-protect/terraform-aws-domain-protect

---

or we can use this for now

```hcl
module "domain_protect" {
  source = "git::https://github.com/domain-protect/domain-protect.git"

  # input variables
}
```

Steps

1. remove the aws provider reference
1. remove backend s3 reference
1. remove the enforced workspace
1. remove any environment specific inputs and toggles since these are used to switch between 2 separate env inputs
    - which means we can only use 2 environments, why not staging or test envs?
    - removing the restriction to 2 hard coded envs allows doing that in the calling, root module resulting in a more scalable module

**Comment by paulschwarzenberger** [comment]
Hi @nitrocode thanks for raising this issue, it would be a good idea to refactor as a Terraform module and as you say the repo is largely structured in the correct way. There would be some other changes required as well as the repo name, such as changing the name of the modules directory and renaming sub-modules.

Potentially we could create a new repo with the correct format, and after publishing, update the existing `domain-protect` repo to simply point to the module, to ensure that existing customer installations continue to work after upgrading.

**Comment by nitrocode** [comment]
Yes, agreed, a new repo makes more sense as a lot of users still point to this repo and the hashicorp registry enforces a strict naming convention (opentofu does not).

I.e. terraform registry mandates that the module repository name be `<org>/terraform-aws-domain-protect` in order to use a `source` of `<org>/domain-protect/aws`. More reason to use a new repo.

**Comment by nitrocode** [comment]
The other issue is more pressing where the current module is a root module rather than a consumable module.

The difference is that the root module must be copied (or forked) with a plan/apply directly in the copied code and in the appropriate workspace, whereas a consumable module (publishable on the registry) can reuse all the code in this repo without a full copy of its contents.

An easy way to do this would be to

- remove the aws provider reference
- remove backend s3 reference
- remove the enforced workspace

from the existing code as these would be defined outside of the module reference.

```hcl
provider aws {
  region = "us-east-2"
}

terraform {
  backend "s3" {
    bucket = "mybucket"
    key    = "path/to/my/key"
    region = "us-east-1"
  }
}

module "domain_protect_dev" {
  source = "git::https://github.com/domain-protect/domain-protect.git?ref=1.0.0"

  # input variables
}

module "domain_protect_prod" {
  source = "git::https://github.com/domain-protect/domain-protect.git?ref=1.0.0"

  # input variables
}
```

**Comment by paulschwarzenberger** [comment]
An initial step to remove the dependency on using Terraform workspace is being covered by [PR 281](https://github.com/domain-protect/domain-protect/pull/281)

**Comment by nitrocode** [comment]
I put in PR #282 to help.

We'd also need to find a way to remove all the `local.env == "dev"` toggles as those are no longer needed if you can call the module multiple times (once per environment).

https://github.com/search?q=repo%3Adomain-protect%2Fdomain-protect%20local.env&type=code
